### ISSUE TITLE
first configuration setup failed to setup

### ISSUE THREAD

**Issue by tferegotto** [andreaprosseda/vimar-byme-plus-homeassistant#1]
Dear Andrea
My compliments for the great work!

I have an issue:
when I try to configure the connection for the first time, the configuration is completed but after I get  an error message "Failed to setup"

add the integration on the vimar view pro, generate the setup code start the configuration process. 

LOG error message:
Registratore: homeassistant.config_entries
Fonte: config_entries.py:594
Prima occorrenza: 19:08:59 (3 occorrenze)
Ultima registrazione: 19:09:41

Error setting up entry <PLANT NAME> for vimar_byme_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/__init__.py", line 21, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/coordinator.py", line 58, in _async_update_data
    return self.client.retrieve_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/vimar/client/vimar_client.py", line 66, in retrieve_data
    return VimarDataMapper.from_list(components)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/vimar/mapper/vimar_data_mapper.py", line 15, in from_list
    _shutters=ShutterMapper.from_list(components),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/vimar/mapper/shutter/shutter_mapper.py", line 14, in from_list
    return [ShutterMapper.from_obj(shutter) for shutter in shutters]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/vimar/mapper/shutter/shutter_mapper.py", line 18, in from_obj
    mapper = ShutterMapper.get_mapper(component)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar_byme_plus/vimar/mapper/shutter/shutter_mapper.py", line 28, in get_mapper
    raise NotImplementedError
NotImplementedError

 - HomeAssistant Version: []
      Core: 2024.10.4
      Supervisor: 2024.11.4
      Operating System: 13.2
      Frontend: 20241002.4

thanks for support

**Comment by andreaprosseda** [comment]
Thanks @tferegotto for your feedback

The fix is released with v1.2.4. Now not implemented entities are discarded during the setup
