### ISSUE TITLE
error: "Connection with gateway is closed"

### ISSUE THREAD

**Issue by ripe89** [andreaprosseda/vimar-byme-plus-homeassistant#13]
Asking for kind help :)
Since few weeks, almost every day the integration fails due to error: "Connection with gateway is closed"
After checking on logs, this is what I found:

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.vimar_byme_plus.vimar.client.web_service.ws_base_vimar
Fonte: custom_components/vimar_byme_plus/vimar/utils/logger.py:37
Integrazione: VIMAR By-me Plus HUB (documentazione, problemi)
Prima occorrenza: 20:45:51 (4 occorrenze)
Ultimo accesso: 20:45:51

Error occurred: RecursionError: maximum recursion depth exceeded
Stack trace: Traceback (most recent call last): File "/usr/local/lib/python3.13/logging/handlers.py", line 1493, in emit self.enqueue(self.prepare(record)) ~~~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/handlers.py", line 1475, in prepare msg = self.format(record) File "/usr/local/lib/python3.13/logging/__init__.py", line 998, in format return fmt.format(record) ~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 712, in format if self.usesTime(): ~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 680, in usesTime return self._style.usesTime() ~~~~~~~~~~~~~~~~~~~~^^ RecursionError: maximum recursion depth exceeded During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/websocket/_app.py", line 672, in _callback callback(self, *args) ~~~~~~~~^^^^^^^^^^^^^ File "/config/custom_components/vimar_byme_plus/vimar/client/web_service/ws_base_vimar.py", line 68, in _on_open self.on_open(ws) ~~~~~~~~~~~~^^^^ File "/config/custom_components/vimar_byme_plus/vimar/client/web_service/ws_attach_phase.py", line 20, in on_open self.on_message(ws, message=session_response) ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/vimar_byme_plus/vimar/client/web_service/ws_attach_phase.py", line 30, in on_message request = callback(message) File "/config/custom_components/vimar_byme_plus/vimar/service/operational_service.py", line 113, in on_attach_message_received self.handle_keep_alive(response) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^ File "/config/custom_components/vimar_byme_plus/vimar/service/operational_service.py", line 152, in handle_keep_alive self._keep_alive_handler.reset() ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/vimar_byme_plus/vimar/scheduler/keep_alive_handler.py", line 30, in reset self._start_timer() ~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/vimar_byme_plus/vimar/scheduler/keep_alive_handler.py", line 20, in _start_timer self._timer = Timer(self.TIMEOUT, self._execute, name="KeepAliveHandler") ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/vimar_byme_plus/vimar/utils/thread.py", line 9, in __init__ log_debug(__name__, f"New Timer created: {self.name}") ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/vimar_byme_plus/vimar/utils/logger.py", line 32, in log_debug logger.debug(message) ~~~~~~~~~~~~^^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 1507, in debug self._log(DEBUG, msg, args, **kwargs) ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 1664, in _log self.handle(record) ~~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 1680, in handle self.callHandlers(record) ~~~~~~~~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 1736, in callHandlers hdlr.handle(record) ~~~~~~~~~~~^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/logging.py", line 41, in handle self.emit(record) ~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/handlers.py", line 1495, in emit self.handleError(record) ~~~~~~~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.13/logging/__init__.py", line 1075, in handleError traceback.print_exception(exc, limit=None, file=sys.stderr) ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/traceback.py", line 129, in print_exception te = TracebackException(type(value), value, tb, limit=limit, compact=True) File "/usr/local/lib/python3.13/traceback.py", line 1044, in __init__ self.stack = StackSummary._extract_from_extended_frame_gen( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ _walk_tb_with_full_positions(exc_traceback), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ limit=limit, lookup_lines=lookup_lines, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ capture_locals=capture_locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/traceback.py", line 472, in _extract_from_extended_frame_gen for f, (lineno, end_lineno, colno, end_colno) in frame_gen: ^^^^^^^^^ File "/usr/local/lib/python3.13/traceback.py", line 404, in _walk_tb_with_full_positions positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti) RecursionError: maximum recursion depth exceeded
Error occurred: AttributeError: 'NoneType' object has no attribute 'sock'
Stack trace: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/websocket/_app.py", line 511, in setSock dispatcher.read(self.sock.sock, read, check) ^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'sock'

**Comment by andreaprosseda** [comment]
Hi @ripe89,
can you send me the entire log? I would like to understand the exact moment when integration fails.
You can send me the log here, via email or Facebook

**Comment by ripe89** [comment]
[Uploading home-assistant_2024-12-30T15-39-41.743Z.log…]()
